--- #Playbook to install junit application in all hosts
- hosts: all
  become: yes
  become_user: ansible
  become_method: sudo
  connection: ssh
  serial: 2
  gather_facts: yes
  vars_files:
  - variables.yaml
  tasks:
  - name: Make Sure app directory exists
    file: path="/app" mode=0755 owner=ansible group=ansible state=directory
  - name: Install wget 
    yum: name=wget state=latest
  - name: Clean Existing app
    raw: sudo rm -rf /app/*
  - name: Get the latest version
    get_url: url='{{ revision1 }}'  dest=/app mode=0755 owner=ansible backup=yes
  - pause:
      seconds: 10
