--- #Playbook to install junit application in all hosts
- hosts: nuvera
  become: yes
  become_user: ansible
  become_method: sudo
  connection: ssh
  serial: 1
  gather_facts: yes
  vars_files:
  - variables.yaml
  tasks:
  - name: Make Sure app directory exists
    file: path="/app" mode=0755 owner=ansible group=ansible state=directory
  - name: Install wget 
    yum: name=wget state=latest
  - name: Clean Existing App Directory
    raw: sudo rm -rf /app/*
  - name: Get the latest version
    get_url: url='{{ Version1.1 }}'  dest=/app mode=0755 owner=ansible group=ansible
  - pause:
      seconds: 10
